### PR TITLE
Fix shellcheck SC1090

### PR DESCRIPTION
**Pull request by randomshell**
Can't follow non-constant source. Use a directive to specify location.

### CODE REVIEW

**Comment by randomshell** [comment]
It is already included in `.github/workflows/lint.yml`. Sorry

**Comment by angristan** [comment]
Shellcheck seems to be fine though: https://github.com/angristan/nginx-autoinstall/actions?

**Comment by randomshell** [comment]
The shellcheck action reads the .yml file, IDEs read the inline comments.

There is also a configuration file that shellcheck reads at startup but it's not YAML https://github.com/koalaman/shellcheck/issues/725#issuecomment-469102071

**Comment by angristan** [comment]
What editor/IDE do you use that shows you these warnings?

**Comment by randomshell** [comment]
I use Visual Studio Code with shellcheck and shell-format extensions.

**Comment by angristan** [comment]
That's too bad, but I'd rather keep shellcheck comments out. We could have used a `.shellcheckrc` file but the vscode extension does not support it (and the action probably doesn't).

**Comment by randomshell** [comment]
> We could have used a .shellcheckrc file but the vscode extension does not support it (and the action probably doesn't).

The extension is a wrapper around shellcheck so I tested and it reads it. I'd like this idea since action files aren't read by a local DEV environment where we do the coding.

**Pull request closed without merging**
