### PR TITLE
Add TLS Dynamic Record Resizing for nginx stable

### PR DESCRIPTION
**Pull request by SoftCreatR**
Closes #131

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Tested on nginx/1.18.0

**Comment by ezar** [comment]
Seems that incorrect patch applied

**Comment by SoftCreatR** [comment]
> Seems that incorrect patch applied

Why? The patch that is being applied is for `NGINX 1.17.7+` and during my test, there was no problem.

**Comment by ezar** [comment]
Seems that is not correct merged --> https://github.com/angristan/nginx-autoinstall/commit/b835cc017f9e85aa128ca74d3d3d1a6fadd6bc71

I'm try to use in 1.18 version and doesn't apply.

**Comment by SoftCreatR** [comment]
How do you know that it doesn't apply? Any errors during the compilation? Because all I did in this PR was to remove the version check, because the patch itself is compatible with both, mainline and stable (as of now).

**Comment by ezar** [comment]
Yes! Seems that current master version doesn’t have your changes: https://github.com/angristan/nginx-autoinstall/blob/master/nginx-autoinstall.sh

**Comment by SoftCreatR** [comment]
Ah, i see.

@angristan a1ad5678409afd408158c20807cca3a420bb7e5e 😏

**Comment by angristan** [comment]
Sorry, I messed up a rebase :( fixed

**Comment by SoftCreatR** [comment]
> Sorry, I messed up a rebase :( fixed

Are you going to merge the ci-lint branch into master?

**Pull request merged**
