### PR TITLE
Fix BoringSSL build

### PR DESCRIPTION
**Pull request by shirtjs**
I added the cc-opt -Wno-ignored-qualifiers to the nginx options. Without it, I got a build error.

### CODE REVIEW

**Comment by randomshell** [comment]
Fixes #127

**Comment by angristan** [comment]
@shirtjs I can't reproduce on Debian 10, which OS were you using?

**Comment by shirtjs** [comment]
> @shirtjs I can't reproduce on Debian 10, which OS were you using?
I was using Ubuntu 19.10.

**Comment by angristan** [comment]
Still can't reproduce, can you tell me what options you used? Thanks 👍

**Comment by shirtjs** [comment]
I was using Stable 1.16.1 with all modules except for ModSecurity.

**Comment by angristan** [comment]
Ok, it seems to happen when pagespeed is installed alongside quiche... Thanks for the fix

**Pull request merged**
