### PR TITLE
Block nginx installation from APT using pinning

### PR DESCRIPTION
**Pull request by skid9000**
Just had a problem in the afternoon with a script that had "apt -y install nginx-full" in it, so here is a little security to prevent that :)

### CODE REVIEW

**Comment by Angristan** [comment]
Is it really necessary to download another file just for 3 lines?

**Comment by skid9000** [comment]
you can do a echo in the file I guess

**Comment by skid9000** [comment]
Done.

**Comment by Angristan** [comment]
Thanks

**Pull request merged**
