### PR TITLE
nginx-autoinstall.sh: Update Nginx mainline to v1.19.8

### PR DESCRIPTION
**Pull request by whalehub**
See https://nginx.org/en/CHANGES

### CODE REVIEW

**Comment by angristan** [comment]
Looks like Github actions is broken: https://www.githubstatus.com/incidents/s654n76c1bwr

I'll wait for the checks to pass before merging :)

**Comment by angristan** [comment]
Looks like the QUIC patch doesn't work anymore?

**Comment by whalehub** [comment]
@angristan Indeed, it apparently needs to be updated for nginx v1.19.7+: https://github.com/cloudflare/quiche/issues/859

**Comment by xopez** [comment]
Since 1.19.10 is already out for mainline you should maybe change that version herer to. The problem with quiche is not fixed. Here is a little bit more info: #cloudflare/quiche#936

**Comment by jxlarrea** [comment]
I don't really think they care enough to fix this.

**Comment by whalehub** [comment]
> I don't really think they care enough to fix this.

@jxlarrea The good news is that the Nginx devs started working on adding native HTTP/3 support to Nginx [more than a year ago](https://www.nginx.com/blog/introducing-technology-preview-nginx-support-for-quic-http-3/), so it's only a matter of time until the Quiche patch for Nginx becomes obsolete.

**Comment by jxlarrea** [comment]
> > I don't really think they care enough to fix this.
> 
> @jxlarrea The good news is that the Nginx devs started working on adding native HTTP/3 support to Nginx [more than a year ago](https://www.nginx.com/blog/introducing-technology-preview-nginx-support-for-quic-http-3/), so it's only a matter of time until the Quiche patch for Nginx becomes obsolete.

Do you know if anyone is using that branch in production? I wonder if it's actually usable.

**Comment by whalehub** [comment]
> Do you know if anyone is using that branch in production? I wonder if it's actually usable.

No idea. The announcement from a year ago says that it shouldn't be used in production since the HTTP/3 standard hasn't been finalized yet, which is still the case today. I wouldn't expect it to be ready for production until after the IETF publishes HTTP/3 as an RFC and HTTP/3 support lands in OpenSSL.

**Comment by xopez** [comment]
A short overview of supported browsers: https://caniuse.com/http3

**Comment by angristan** [comment]
In https://github.com/angristan/nginx-autoinstall/pull/191, I disabled the patch in the CI and added some warnings. Hopefully there will be way to have HTTP/3 on recent versions soon, either from Cloudflare or Nginx. 🙂

**Comment by MaximeMichaud** [comment]
> In #191, I disabled the patch in the CI and added some warnings. Hopefully there will be way to have HTTP/3 on recent versions soon, either from Cloudflare or Nginx. 🙂

They are working on it, but right now this is fucktop. Cloudflare should have fix the patch and NGINX release HTTP3.
Same for OPENSSL.

**Pull request closed without merging**
