### PR TITLE
Update Nginx, OpenSSL and LibreSSL

### PR DESCRIPTION
**Pull request by skid9000**
I am testing right now if everything works as it should, will comment when everything is working.

Nginx :

* Mainline 1.17.0
* Stable 1.16.0

OpenSSL 1.1.1c
LibreSSL 2.9.2

TESTING :
(every module is enabled in each test)

* [x] Nginx Stable + OpenSSL : Works fine.
* [x] Nginx Stable + LibreSSL : OCSP stapling dead.

* [x] Nginx Mainline + OpenSSL : Works fine.
* [x] Nginx Mainline + LibreSSL : OCSP stapling dead.

### CODE REVIEW

**Comment by skid9000** [comment]
So everything compile correctly but it seems that the latests versions of LibreSSL dosen't have OCSP Stapling working 🤔 

https://github.com/libressl-portable/portable/issues/532

Should we push the LibreSSL update anyway ? Since it's the only thing that dosen't work right now...

**Comment by angristan** [comment]
Maybe we can stick with 2.9.0 for now until this is fixed?

**Comment by skid9000** [comment]
I'm testing right now to compile with 2.9.0 and see if it works.

**Comment by skid9000** [comment]
Welp, it works, so we are good to merge :)

2g7x6J

**Comment by angristan** [comment]
Thanks!

**Pull request merged**
