### PR TITLE
Add dependencies for WebDAV

### PR DESCRIPTION
**Pull request by tmiland**
Added dependencies for WebDAV

### CODE REVIEW

**Comment by tmiland** [comment]
Forgot to add dependencies, build will fail if not installed. 

https://github.com/arut/nginx-dav-ext-module#requirements

**Comment by angristan** [comment]
Thanks, can you rebase your branch in master?

**Comment by tmiland** [comment]
> Thanks, can you rebase your branch in master?

Not quite sure how to...

Do you have any specific commands i can run, so i don't mess up? 🤓

**Comment by angristan** [comment]
mmh, let me try something...

**Comment by angristan** [comment]
Merged: https://github.com/angristan/nginx-autoinstall/commit/0cd0ae5615c875ae45b4b11207e3e45b910b54d8

**Comment by angristan** [comment]
Here is what I did, FYI:

```sh
git checkout -b tmiland-nginx-dav-ext-module master
git pull https://github.com/tmiland/nginx-autoinstall.git nginx-dav-ext-module
git checkout master
git merge --squash tmiland-nginx-dav-ext-module
git commit --amend --author "Tommy Miland <youremailaddress>"
git push
```
There are probably other ways 🤷‍♂️

**Comment by tmiland** [comment]
> Here is what I did, FYI:
> 
> ```shell
> git checkout -b tmiland-nginx-dav-ext-module master
> git pull https://github.com/tmiland/nginx-autoinstall.git nginx-dav-ext-module
> git checkout master
> git merge --squash tmiland-nginx-dav-ext-module
> git commit --amend --author "Tommy Miland <youremailaddress>"
> git push
> ```
> 
> There are probably other ways man_shrugging

Thank you @angristan 👍

**Pull request closed without merging**
