### PR TITLE
Testcookie nginx module

### PR DESCRIPTION
**Pull request by tmiland**
Tested and working on two Debian 10 severs. :+1:

### CODE REVIEW

**Comment by angristan** [comment]
Does this module work fine? I see it's not supported anymore since last year

**Comment by tmiland** [comment]
> Does this module work fine? I see it's not supported anymore since last year

Yes, works great. 

This is what I have in nginx.conf:

```nginx
#default config, module disabled
testcookie off;
#setting cookie name
testcookie_name TCK;
#setting secret
testcookie_secret random;
#setting session key
testcookie_session $remote_addr;
#setting argument name
testcookie_arg ckattempt;
#setting maximum number of cookie setting attempts
testcookie_max_attempts 3;
#setting p3p policy
testcookie_p3p 'CP="CUR ADM OUR NOR STA NID", policyref="/w3c/p3p.xml"';
#setting fallback url
testcookie_fallback /cookies.html?backurl=http://$host$uri?$query_string;

#configuring whitelist
testcookie_whitelist {
    1.1.1.1/32;
}
#Process only GET requests, POST requests will be bypassed.
testcookie_get_only off;
#Close connection just after setting the cookie, no reason to keep connections with bots.
testcookie_deny_keepalive on;
#setting redirect via html code
testcookie_redirect_via_refresh off;
#enable encryption
testcookie_refresh_encrypt_cookie on;
#setting encryption key
testcookie_refresh_encrypt_cookie_key random;
#setting encryption iv
testcookie_refresh_encrypt_cookie_iv xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
#setting response template
testcookie_refresh_template '<html><body>setting cookie...<script type=\"text/javascript\" src=\"/aes.min.js\" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("$testcookie_enc_key"),b=toNumbers("$testcookie_enc_iv"),c=toNumbers("$testcookie_enc_set");document.cookie="TCK="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";location.href="$testcookie_nexturl";</script></body></html>';

```

```nginx
	# Whitelisting testcookie with "map"
	map $remote_addr $trusted {
		default          0;
		"127.0.0.1"      1; # localhost
	}
```

And in server block:
```nginx
  location / {
.....
      testcookie on;
      testcookie_pass $trusted;
.....
}
```

Notice the
```nginx
#setting redirect via html code
testcookie_redirect_via_refresh off;
```
Which turns off the html part.

See https://github.com/kyprizel/testcookie-nginx-module#testcookie_redirect_via_refresh

**Comment by angristan** [comment]
OK, could you add something like this to `conf/README.md`?

**Comment by tmiland** [comment]
> OK, could you add something like this to `conf/README.md`?

Done. :+1:

**Comment by angristan** [comment]
Thanks!

**Comment by angristan** [comment]
Oh I almost forgot, we need to update README.md too :)

**Comment by tmiland** [comment]
> Thanks!

My pleasure! 

> Oh I almost forgot, we need to update README.md too :)

Re-added. :+1: 

It vanished on the lua merge :sweat_smile:

**Pull request merged**
