### PR TITLE
Add ngx_cache_purge

### PR DESCRIPTION
**Pull request by Angristan**
https://github.com/FRiCKLE/ngx_cache_purge

from https://github.com/Angristan/nginx-autoinstall/issues/41#issuecomment-366427835

### CODE REVIEW

**Comment by Angristan** [comment]
@Firegarden I looked the repo but did not find how to trigger the purge. Is it via a certain HTTP request?

Also, I will test the PR tomorrow

**Comment by Angristan** [comment]
Tested ✅

```
       Installing dependencies        [OK]
       Downloading ngx_cache_purge    [OK]
       Downloading Nginx              [OK]
       Configuring Nginx              [OK]
       Compiling Nginx                [OK]
       Installing Nginx               [OK]
       Restarting Nginx               [OK]
       Removing Nginx files           [OK]

       Installation successful !

       Installation log: /tmp/nginx-autoinstall.log

root@nginx:~# nginx -V
nginx version: nginx/1.12.2
built by gcc 6.3.0 20170516 (Debian 6.3.0-18) 
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --without-http_ssi_module --without-http_scgi_module --without-http_uwsgi_module --without-http_geo_module --without-http_split_clients_module --without-http_memcached_module --without-http_empty_gif_module --without-http_browser_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_mp4_module --with-http_auth_request_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --add-module=/usr/local/src/nginx/modules/ngx_cache_purge
```

**Comment by benhartwich** [comment]
Hi, 

when will you merge this branch with the master branch?

**Comment by Angristan** [comment]
I wanted to know how to use it https://github.com/Angristan/nginx-autoinstall/pull/45#issuecomment-366550649

**Comment by VirtuBox** [comment]
Hello,

you just need to set choose an URL to purge the cache.
Example with fastcgi_cache ; 
```
location ~ \.php$ {
  try_files $uri =404;
  include fastcgi_params;
  fastcgi_pass php;
  fastcgi_cache_bypass $skip_cache;
  fastcgi_no_cache $skip_cache;
  fastcgi_cache WORDPRESS;
}
location ~ /purge(/.*) {
  fastcgi_cache_purge WORDPRESS "$scheme$request_method$host$1";
  access_log off;
}
```

Example with proxy_cache
```
server {
        location / {
            proxy_pass         http://127.0.0.1:2368;
            proxy_cache        GHOST;
            proxy_cache_key    $uri$is_args$args;
        }

        location ~ /purge(/.*) {
            allow              127.0.0.1;
            deny               all;
            proxy_cache_purge  GHOST$1$is_args$args;
        }
    }
```

**Comment by benhartwich** [comment]
Great examples, I´ve still implemented this on a fork.

**Comment by Angristan** [comment]
What does it do that [proxy_cache_purge](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_purge) doesn't?

**Comment by VirtuBox** [comment]
paid

**Comment by Angristan** [comment]
Oh ok >-<

**Comment by Firegarden** [comment]
I am just seeing this now. This is sweet thank you. 

There is a wordpress plugin that will purge this cache as well as the mentioned url
 #location ~ /purge(.*) {
    #    fastcgi_cache_purge WEBCACHESERVER "$request_method-$scheme://$host$1";
    #}
The wordpress plugin is called Nginx Helper by rtCamp

**Comment by Dark9Y8** [comment]
@Firegarden  Yes, that plugin was good but now sometimes it just doesn't work. Also, it is not updated for a long time. I can also see that creators are not active on their easyengine project as well. I was using RtCamp's nginx based solution for my hosting. Now, I'm a big fan of this script! ;) More control, More Power!

**Pull request merged**
